### ISSUE TITLE
Processing.instances is empty

### ISSUE THREAD

**Issue by teo1978** [processing-js/processing-js#153] opened 2015-03-16 21:53 UTC
Either something is broken, or the information at http://processingjs.org/articles/jsQuickStart.html#accessingprocessingfromjs is not accurate.

It says:
> By default, when a `<canvas>` has a data-processing-sources attribute, its id is used as a unique identifier for the Processing instance. If no id attribute is provided, you can use Processing.instances[0]

The second statement is untrue.
I have tried Processing.instances and it always return an empty array (whether or not the canvas has an id); Processing.instances[0] is undefined.

**Comment by GoToLoop** [comment] 2015-03-16 22:02
I've come across that mismatch information 1 year ago!
What worked for me was **getProcessingSketchId()** though.
Unfortunately in "CoffeeScript Mode", it was renamed to **getProcessingSketchID()**, breaking consistency!

```js
(function waitPJS() {
  var pjs = Processing.getInstanceById(getProcessingSketchId());

  if (pjs)  begin(pjs);
  else      setTimeout(waitPJS, 1000);

  console.log(pjs);
}
)();
```

**Comment by Pomax** [comment] 2015-03-18 18:57
Hmm, while you generally want to use `Processing.getInstanceById(...the element's id...)`, Processing.instances should also be externally visible. Marking as bug

**Comment by Pomax** [comment] 2015-03-20 01:16
after review this is a documentation error - the internal container is called `processingInstances`. I'll update the article text for that.

**Closed by Pomax** 2015-03-20 01:16 UTC
Labels: bug

**Comment by Pomax** [comment] 2015-03-20 01:37
digging deeping, `.instances` is the correct name, and after several tests, Processing.instances contains the list of sketches every time. The only time they don't is if `exit()` is called on the sketch, at which point it's taken out of the list (the ref tests, for instance, will run hundreds of tests, but Processing.instances will almost always look empty because ref tests exit after the first frame)

**Comment by teo1978** [comment] 2015-03-20 09:54
Do you mean without having applied any fix? Because I have observed the issue wheile definitely NOT calling exit(), not explicitely in the sketch at least. I'll retry and post an example sketch (but i think it was just a dummy sketch with empty setup() and draw() methods)

Maybe i was testing a sketch without a draw method. Which makes me question: WHY should a sketch be removed from instances after exciting?
I don't see a good reason. You do can get them by name, so that's inconsistent. You should always be able to access instances, and if they are exited, have a property or method to check that. (or even a separate activeInstances array of you want)

**Comment by GoToLoop** [comment] 2015-03-20 12:31
Me too never had any success reading from _Processing.instances_!  =(

**Comment by Pomax** [comment] 2015-03-20 15:59
yep, without any fix. As simpler test, if you fire up the `test.html` in the main dir, and this consult Processing.instances in the console, you should see it being an array with a single sketch object. As for why the sketch gets removed: because it's no longer running. exit() unloads everything, if we didn't remove it from .instances the memory would never be cleaned up, which is important when you use multiple sketches on a page.

Do you have an example page (jsbin/jsfilddle/etc) where you have sketches loaded but where Processing.instances has no content?

**Comment by GoToLoop** [comment] 2015-03-20 18:00
* _Processing.instances[]_ was my very 1st attempt!
* Only had to use **Processing.getInstanceById(getProcessingSketchId())** when the latter failed!
* Also, my experience w/ PJS is 100% from "JavaScript Mode".
* Firing up some "http-server/live-server/python -m SimpleHTTPServer, etc." isn't a usability option!
* A short example demoing that _Processing.instances[]_ is always empty w/ "JS Mode":

#### "ProcessingInstanceTest.pde":

```processing
void setup() {
  size(400, 300, JAVA2D);
  smooth(4);
  frameRate(.5);
}

void draw() {
  background((int) random(#000000));
}
```

#### "Instances.js":

```js
(function waitInstance() {
  var pjs, instances = Processing.instances;

  if (instances)  pjs = instances[0];

  console.log(instances);
  console.log('Processing.instances[0]: \t' + pjs);
  //console.log(Processing.getInstanceById(getProcessingSketchId()));

  if (pjs)  pjs.println("Got " + pjs);
  else      setTimeout(waitInstance, 1000);
}
)();
```

**Comment by Pomax** [comment] 2015-03-20 19:38
I strongly suspect your `instances.js` is asking for the first instance in the `Processing.instances` list before a sketch has been bound. Just because "pjs" is available does not mean that `Processing.instances[0]` will exist, too. Pjs will be available before it loads and executes its first sketch, so it seems likely this is tapping into `.instances` too early, and should at the very least keep waiting until `Processing.instances.length > 0`?

As for firing up a local server to see whether Pjs is misbehaving: you're commenting in the Processing.js project's issue tracker, I'm assuming you're willing to help figure out whether this is a bug in Processing.js or not, in which case that suggestion is the first step in determining where the bug lives. If Pjs itself works fine as per that test, then we know the bug is not in Pjs but in either your code, or how Processing works with Pjs. In this case, I'm going with likely the first given the code you've shown.

**Comment by GoToLoop** [comment] 2015-03-20 20:03
> ... and should at the very least keep waiting until `Processing.instances.length > 0`?

* I suspected you haven't run my example!
* `console.log(instances);`, which is `Processing.instances`, explicitly displays an empty array!
* And `setTimeout(waitInstance, 1000);` re-runs the whole thing @ 1 FPS forever!

**Comment by teo1978** [comment] 2015-03-20 20:09
Excuse an OT question: when you release a new (stable) version of processing.js, does it somehow automagically get included into JavaScript Mode (meaning for any new download of JavaScript Mode), or do you do a pull request (or something) to the JavaScript Mode project, or is it completely up to those who (don't) maintain JavaScript Mode to get the latest version of processing.js?

**Comment by Pomax** [comment] 2015-03-20 20:13
nope, we literally have **zero** ties to Processing, so any updates in the PDE are entirely up to when they get round to updating and releasing a new PDE I think? If you're trying to find problems in Processing.js, then relying on what Processing bundles with the PDE is not going to be helpful (it'll almost always be behind the proper release version of Pjs)

**Comment by teo1978** [comment] 2015-03-20 20:16
I'm not talking about Processing IDE, I'm talking about the JavaScript Mode, which does not come bundled with Processing, and you install separately through "add mode".

**Comment by teo1978** [comment] 2015-03-20 20:17
but I guess you have answered anyway ;)

**Comment by Pomax** [comment] 2015-03-20 20:19
@GoToLoop I did try your code, in fact I have it in jsbin as http://jsbin.com/tunigazoto/1 - let me know if that works for you, but I clearly see `instances` having 1 object i it?

**Comment by Pomax** [comment] 2015-03-20 20:20
@teo1978 we have no ties to that either, I'm think that's maintained by @fjenett ?

**Comment by teo1978** [comment] 2015-03-20 20:22
> As for why the sketch gets removed: explicitly calling exit() means the sketch gets destroyed - it is no longer a running instance or indeed an instance at all, and needs to be garbage collected

That makes sense, but I hope you *don't* do that when the sketch is exited "implicitly", i.e. in the case of a sketch with no draw() (or no draw() and no setup())... do you?

**Comment by GoToLoop** [comment] 2015-03-20 20:24
* I've recently installed Processing 3.0a5 in a laptop w/ Win8.1
* JavaScript Mode is @ version 1.3.1.
* And inside its "\template\" subfolder, the "processing.js" file is still @ version 1.4.1!
* But it's very easy to replace it w/ something else.  ;-)

**Comment by teo1978** [comment] 2015-03-20 20:26
Right, latest version of processing.js downloaded from here works as expected.

The one included in JavaScript Mode is actually 1.4.1

**Comment by Pomax** [comment] 2015-03-20 20:27
Yeah, I can see why 1.4.1 would cause grief - that's a release from August 2012. The first release that went closer to the 2.0 API was 1.4.7 (march 2014), and with the current XML etc patches landed the latest version is 1.4.12

**Comment by GoToLoop** [comment] 2015-03-20 20:32
@Pomax, it works there. But it's moot b/c regular Processing users, like me too,  would use "JS Mode"!
@teo1978, in my example the sketch never ends and Processing.instances is always an empty array in "JavaScript Mode"!

**Comment by Pomax** [comment] 2015-03-20 20:34
right, so that's a thing you should notify the JavaScript mode maintainer about, then, so they can update their Pjs version, that's not something I can control

**Comment by teo1978** [comment] 2015-03-20 20:35
Let's file a feature request to JavaScript Mode to automatically keep processing.js up to date by downloading it from here.
For that to be possible, though, don't they need you to make the "compiled" processing.js file available at a static URL? Or is it already?

**Comment by Pomax** [comment] 2015-03-20 20:36
it is already, it's available both on bower.io (for people who like the bower package manager) and on npmjs.org (for pretty much everyone else =)

**Comment by GoToLoop** [comment] 2015-03-20 20:37
Just replaced bundled "/template/processing.js" to version 1.4.8 and still _Processing.instances[]_ yields an ternal empty array!

**Comment by Pomax** [comment] 2015-03-20 20:39
@GoToLoop: it doesn't make sense to try a "still over a year old" version, try 1.4.12 and see if it works for you.

**Comment by GoToLoop** [comment] 2015-03-20 20:43
"JS Mode"'s generated "/template/template.html" file for my example:

```html
<!DOCTYPE html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title>@@sketch@@ : Built with Processing and Processing.js</title>
		<link rel="icon"  type="image/x-icon" href="data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAQAAVzABAEAjBQAaDwYAWjUGAGE6CQBrQQ0ATS8PAFhAJwBUQC8AbFI6AHVXPACBZk4A4NrWAPb19QAAAAAAAMmZmZmZmgAJIwAAAAAAcMIjPjA+PjAKpxIuMDMzMAm0Ii4zMzMACaIiLt3dMAAJtyIuIzPQAAm0Un5yM+IzKLRkfncy4iIotRF+dyLkIiq0QX53F+EiGrQUTkd34iIatEVu7u5iIVrBVVRBRFRVbAtGZGZla2uwAMu7u7u8vADAAwAAgAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIABAADAAwAA" />
		<meta name="Generator" content="Processing" />
		<!-- - - - - - - - - - - - - - - - - - - - - 
		+
		+    Wondering how this works? 
		+
		+    Go to: http://processing.org/
		+    and: http://processingjs.org/
		+
		+ - - - - - - - - - - - - - - - - - - - - -->
		<style type="text/css">
	body {
	  background-color: #333; color: #bbb; line-height: normal;
	  font-family: Lucida Grande, Lucida Sans, Arial, Helvetica Neue, Verdana, Geneva, sans-serif;
	  font-size: 11px; font-weight: normal; text-decoration: none;
		  line-height: 1.5em;
	}
	a img { 
		border: 0px solid transparent;
	}
	a, a:link, a:visited, a:active, a:hover { 
		color: #cdcdcd; text-decoration: underline;
	}
	h1 {
	    font-family: Arial, Helvetica Neue, Verdana, Geneva, sans-serif;
		width: 100%; letter-spacing: 0.1em;
		margin-bottom: 1em; font-size: 1.65em;
	}
	canvas { 
		display: block; 
		outline: 0px; 
		margin-bottom: 1.5em; 
	}
	#content { 
		margin: 50px auto 0px auto; padding: 25px 25px 15px 25px;
		width: @@width@@px; min-width: 300px; overflow: auto;
		border-left: 1px solid #444; border-top: 1px solid #444; 
		border-right: 1px solid #333; border-bottom: 1px solid #333;
		background-color: #3d3d3d;
	}
		</style>
		<!--[if lt IE 9]>
			<script type="text/javascript">alert("Your browser does not support the canvas tag.");</script>
		<![endif]-->
		<script src="processing.js" type="text/javascript"></script>
		@@scripts@@
	</head>
	<body>
		<div id="content">
			<div>
				<canvas id="@@id@@" data-processing-sources="@@sketch@@.pde" 
						width="@@width@@" height="@@height@@">
					<p>Your browser does not support the canvas tag.</p>
					<!-- Note: you can put any alternative content here. -->
				</canvas>
				<noscript>
					<p>JavaScript is required to view the contents of this page.</p>
				</noscript>
	    	</div>
			<h1>@@sketch@@</h1>
    		<p id="description">@@description@@</p>
			<p id="sources">Source code: @@source@@</p>
			<p>
			Built with <a href="http://processing.org" title="Processing">Processing</a>
			and <a href="http://processingjs.org" title="Processing.js">Processing.js</a>
			</p>
		</div>
	</body>
</html>
```

**Comment by teo1978** [comment] 2015-03-20 20:45
Would you mind giving us the url? I can't seem to find it by searching on bower.io or npmjs.org (through the user search engine).

**Just in case** we're not talking about the same thing (I don't know how these package thingies work), I mean an url like http://somewhere.xxx/processing.js so that the IDE on the user's side can automatically check for updates and download it, without the maintainers of JavaScript mode having to release a new version of JavaScript Mode every time a new version of Processing.js is available.

**Comment by GoToLoop** [comment] 2015-03-20 20:45
I didn't know PJS was @ version 1.4.12 already, since http://ProcessingJS.org/ still points to v1.4.8 as the latest version!

**Comment by Pomax** [comment] 2015-03-20 20:47
teo

**Comment by teo1978** [comment] 2015-03-20 20:49
> I didn't know PJS was @ version 1.4.12 already, since http://ProcessingJS.org/ still points to v1.4.8 as the latest version!

Speaking of which, please review:
https://github.com/processing-js/processing-js/issues/139

**Comment by Pomax** [comment] 2015-03-20 20:49
@GoToLoop yeah the website is not updated in lockstep mostly because the changes made to the library itself aren't used by any of the scripts that run on the site (there's some processing code but that doesn't use any of the more complex things that might be broken in 1.4.8)

**Comment by Pomax** [comment] 2015-03-20 20:52
hmmm... that is illegal HTML, @GoToLoop. `instances` taps into the canvas `id` attribute, and it's possible that because that has an illegal value (ids may **only** start with the letters a-z and A-Z) the instance binding doesn't work as intended. That seems like a bug definitely worth filing on the "JavaScript mode" project issue tracker.

**Comment by GoToLoop** [comment] 2015-03-20 21:02
* That version 1.4.12 is incompatible w/ "JavaScript Mode" and completely deviates from version 1.4.8!
* Also there's no way to tell which version the file is by looking inside it!
* There are strange things like `module.exports = function(options, undef) {`.
* It doesn't seem to be a stand-alone file at all. That's very sad!

**Comment by Pomax** [comment] 2015-03-20 21:11
That is unfortunate, and something the JavaScript mode maintainers will have to solve, then. Processing.js is intended as browser library, and has been generated for that purpose. If the "JavaScript mode" project made specific assumptions on how to load it in, rather than as plain browser library, that is something they need to fix.

As for versioning, `Processing.version` will tell you which version it is, and can be easily found in the non-minified version (it's the "version" property number in the very first module) and still findable by searching for `"version"` in the minified library.

As you can't tell me that jsbin works and then say "It doesn't seem to be a stand-alone file at all. That's very sad!": you **know** it works as stand-alone because you're **literally** seeing it used on its own in that jsbin. If you are frustrated that "JavaScript mode" doesn't work with the current Processing.js, direct that at the people who can fix that by filing issues over at their project's issue tracker.

**Comment by GoToLoop** [comment] 2015-03-20 21:31
>  Processing.js is intended as browser library,...
* If that's so, why the insistence on matching Java Mode's API 99%?
* Methinks p5*js framework is more appropriate as a free-lance framework!

> _Processing.version_ will tell you which version it is, and can be easily found in the non-minified version...

* I believe if the source ".js" file is well indented and human readable it is non-minified, right?
* Up till version 1.4.8 I could easily find its version in a readable form inside "processing.js".
* Where is it currently now? Why is it hidden?

> ... and those assumptions were invalidated when Processing.js added support for commonjs/AMD/window-fallback,

Can't we have a non-chic regular "processing.js" version like we always had up till version 1.4.8?

**Comment by Pomax** [comment] 2015-03-20 21:48
1. see all the previous bugs where that was discussed. Locking this tread as "yet again, this is being dragged up".
2. feel free to use p5.js...? I don't get why you'd say this, is this supposed to be a threat? Different projects have different purposes, if you like p5.js better, *go use p5.js". Don't use it as a weapon to pressure other projects into doing what *you* want. If anything, fork what you feel isn't going in the right direction. It's Open Source, you can do that.
3. If you say so? The non-minified version is simply the `processing.js` file as it comes rolling out of browserify. If you want even more basic source, there's the `src` dir that's used to generate pjs.
4. that's still true. Opening a file in a text editor and hitting "search", then typing `"version"` and looking at the number you see is something anyone can do.
5. scroll up, and read the comment that already tells you
6. no
7. that is irrelevant, "JS mode" is not our project, Pjs has no ties to it, and is not going to go back to an unmaintainable file just for the sake of supporting a project that has nothing to do with it. 

Do you want JS mode improved? Go to https://github.com/fjenett/javascript-mode-processing/issues

Any other PR or comment that gets polluted with this subject I will start locking down. We covered this topic, and this is turning into a toxic project contribution. File issues on this repo if there are bugs in Pjs, or you suspect there are and you need them verified. One issue per bug, and if you have a PR already written to fix it: sweet, one PR per bug to fix. Anything else is off topic and will likely end up closed or deleted.
